server:
  port: 3000

db:
  type: 'postgres'
  database: 'dao27n3011rmfi'
  host: 'ec2-3-211-176-230.compute-1.amazonaws.com'
  port: 5432
  username: 'ljeylpqrfidjmm'
  password: 'bf5234feab8a3ff6337fe7f0e8a1fda67de643199b4fef50d60c2f1c2a1020c6'
  synchronize: true

jwt:
  secret: 'jfal24dfaee324'
#  expiresIn: 3600