server:
  port: 3000

db:
  type: 'postgres'
  database: 'itihas'
  host: 'itihas.c9zchczwypcl.ap-south-1.rds.amazonaws.com'
  port: 5432
  username: 'itihas'
  password: 'itihas123'
  synchronize: true

jwt:
  secret: 'jfal24dfaee324'
#  expiresIn: 3600
